### ISSUE TITLE
overwriting asdf files

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf#100]
This isn't urgent, I am simply reporting it so it's not forgotten.
When attempting to overwrite an asdf file on Windows I get an error:

```
In [17]: f1.write_to('foc2sky.asdf')
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-17-1418e770a532> in <module>()
----> 1 f1.write_to('foc2sky.asdf')

C:\Anaconda\envs\gwcs\lib\site-packages\pyasdf-0.0.dev417-py2.7.egg\pyasdf\asdf.
pyc in write_to(self, fd, all_array_storage, all_array_compression, auto_inline,
 pad_blocks)
    586         original_fd = self._fd
    587
--> 588         self._fd = fd = generic_io.get_file(fd, mode='w')
    589
    590         self._pre_write(fd, all_array_storage, all_array_compression,

C:\Anaconda\envs\gwcs\lib\site-packages\pyasdf-0.0.dev417-py2.7.egg\pyasdf\gener
ic_io.pyc in get_file(init, mode, uri)
   1033             realpath = url2pathname(parsed.path)
   1034             return RealFile(
-> 1035                 open(realpath, realmode), mode, close=True,
   1036                 uri=uri)
   1037

IOError: [Errno 22] invalid mode ('wb') or filename: 'foc2sky.asdf'

```

On Linux the file is silently overwritten. Perhaps add a `clobber` argument to `write_to` similar to fits.

**Comment by mdboom** [comment]
I'll see if I can reproduce this on Windows (but will have to reboot into Windows first).  I suspect it may because the file is already open under another handle (which is not allowed on Windows, but is on Unix).

I'm not crazy about adding a `clobber` option -- I think it's better for these things to behave the way the OS' underlying file routines behave so there's consistent expectations.  I've always thought the `clobber` in pyfits was a mistake, but I might be in the minority there.

**Comment by embray** [comment]
I agree; I wish I could rip it out.  I don't want to deal with the fallout of that though.  People were mad enough when I made it raise a KeyError if you try to delete a keyword that doesn't exist.

**Comment by mdboom** [comment]
I can't seem to reproduce this on Windows 8.  There must be something more to it than just overwriting a file.  Keeping the file handle open in the same process, or another process, and trying to write to it then works as well.  Can you provide a script to reproduce it?

**Comment by nden** [comment]
There's something strange happening. I can't always reproduce it either. But it seems like it's happening when there's a numpy array in the file. This gives the error:
```
rot = models.AffineTransformation2D([[1,2],[3,4]])
f=AsdfFile()
f.tree={'model': rot}
f.write_to('test.asdf')
f=AsdfFile.read('test.asdf')
model=f.tree['model']
f1=AsdfFile()
f1.tree={'model': model}
f1.write_to('test.asdf')
```
Doing `f.close()` does not help.

**Comment by nden** [comment]
Windows 8.1 here (in case this matters).

**Comment by mdboom** [comment]
Thanks.  My wild guess is that the model is holding a memmapped reference to the file (since the model includes an array, albeit very small).  And on Windows, you can't read from the "old version" of the file while writing to the "new version".  Nothing immediately springs to mind to solve this in general -- deep copying the model before assigning it to the new tree may help (if deep copying of models works in general).

Another thing that springs to mind -- which wouldn't fix this problem in all cases, but would help here -- would be to not memmap but just read in small arrays.  There's really no real need to memory map here.

**Comment by embray** [comment]
I haven't really followed this closely, but if you're reading some data from mmap, then trying open another handle to write to the same file, you can't do that on Windows.  You have to write to a temp file and then copy it over the old one.

**Comment by mdboom** [comment]
Just by chance came across this:

https://boltons.readthedocs.org/en/latest/fileutils.html#atomic-file-saving

It might be useful to solve this problem.  It also seems like a nice facility to have -- preventing half-written files from being left on disk when an exception is raised along the way.

**Comment by embray** [comment]
Sounds worth trying out.

**Comment by drdavella** [comment]
@nden PR #302 adds a test to attempt to reproduce this issue. Since the test passes on AppVeyor, I'm inclined to close the issue unless it's still a problem.

**Comment by nden** [comment]
@drdavella This can be closed, not an issue any more.
