### ISSUE TITLE
problem using `with` to read a file

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf#168]
@mdboom Should I not use `with` to open asdf files? Or am I doing something wrong?

```
ar = np.arange(36).reshape((6,6))
f = AsdfFile()
f.tree = {'regions': ar, 'reftype': 'regions'}
f.write_to('test.asdf')
```

```
with AsdfFile.open('test.asdf') as f:
    reg=f.tree['regions']
print reg
<array (unloaded) shape: [6, 6] dtype: int64>

```

**Comment by mdboom** [comment]
You can use a with block, but it needs to be active as long as you need access to the data.  (The data is memmapped and the memmap handles are closed at the same time as the file handle).  You can also use an explicit `close` if that's easier.

**Comment by nden** [comment]
Right. I knew that. Sorry about the noise.

**Comment by embray** [comment]
I think there should still be more control over this kind of thing.  PyFITS deliberately leaves the mmaps open because it's an implementation detail which most users won't even tend to understand, and not allowing this to work I think discourages use of the `with` statement by users in many cases (for read-only applications it doesn't matter, but there are plenty of write applications where it would be good to use `with`).

Of course, PyFITS has the opposite problem where users think they've closed the file but they really haven't.  I think both should have some way to control this better (but I lean toward leaning mmaps open except when the user has explicitly requested to close them as well).

**Comment by mdboom** [comment]
Yeah -- there's sort of no perfect option here.  A kwarg to indicate whether to close the mmaps automatically might be helpful, though.
