### ISSUE TITLE
diff tool for ASDF files

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf#211]
It'd be good to have this.

**Comment by drdavella** [comment]
Would it make sense to add `diff` as a subcommand to `asdftool`?

**Comment by perrygreenfield** [comment]
Initially, yes, I think so.

**Comment by drdavella** [comment]
Just looking to gather some additional requirements here. Presumably you need to see how the files are different in a specific way, otherwise just using `diff` would be sufficient. What would be useful here? Here's a quick brainstorm of possibilities:

- recursively traverse the trees and identify differences
  - these can be places where the trees have different fields, or where the same fields have different values
- identify cases where the trees refer to the same data blocks but the contents of the blocks differ
