### ISSUE TITLE
Support referencing data (and metadata) in external files that are not ASDF

### ISSUE THREAD

**Issue by Cadair** [spacetelescope/asdf#369]
ASDF currently supports references to data in external ASDF files and expolding ASDF files into multiple files. I would like to be able to reference data (and maybe metadata) in FITS files (preferably in a library independent manner).

What I would want to use this for is to have a collection of FITS files (representing a multi-dim dataset) where the ASDF file provides metadata (WCS information and other things) but the actual data (in 2D frames) is stored in FITS files.

**Comment by jdavies-st** [comment]
Something very close to this is implemented in the `asdf.fits_embed.AsdfInFits` class right now, where the ASDF tree references the data part of FITS HDUs that are contained in the _same_ FITS file.  To use the existing functionality, the FITS file needs to be a single, multi-extension FITS file though instead of multiple files.  Or a single HDU data array can be a n-dimensional array as well - anything that numpy arrays can represent.

We currently use this functionality in the JWST calibration pipeline to store the ASDF tree in FITS files.  So for example, one FITS file can contain multiple slits from a given multi-slit exposure for instance.  The FITS file contains a SCI,DQ,ERR array for each slit, and the ASDF references each of these in the tree.

If one looks at the FITS file with standard FITS readers, the ASDF tree gets pickled into an ImageHDU extension called ASDF.
```
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     343   ()      
  1  SCI           1 ImageHDU        48   (1153, 26)   float32   
  2  ERR           1 ImageHDU        23   (1153, 26)   float32   
  3  DQ            1 ImageHDU        26   (1153, 26)   int32 (rescales to uint32)   
  4  SCI           2 ImageHDU        45   (1352, 28)   float32   
  5  DQ            2 ImageHDU        11   (1352, 28)   int32 (rescales to uint32)   
  6  ERR           2 ImageHDU         9   (1352, 28)   float32   
...
 82  SCI          10 ImageHDU        45   (1433, 28)   float32   
 83  DQ           10 ImageHDU        11   (1433, 28)   int32 (rescales to uint32)   
 84  ERR          10 ImageHDU         9   (1433, 28)   float32   
 91  ASDF          1 ImageHDU         7   (2078043,)   uint8   
```
This allows us to store WCS information in the ASDF that cannot be represented currently by FITS keywords.

We've also built additional functionality to map certain parts of the ASDF tree to FITS header KEYWORDS, which is probably outside of the scope requested here.

I'm just pointing this out here as the documentation is a little sparse.

**Comment by Cadair** [comment]
That sounds like a reasonable place to start, thanks for the heads up.

> We've also built additional functionality to map certain parts of the ASDF tree to FITS header KEYWORDS, which is probably outside of the scope requested here.

This would also potentially be very useful, although the grouping of the data is my first concern.

**Comment by drdavella** [comment]
Just to note here but @Cadair and I had a discussion about this offline which prompted him to open the issue here. I think this sounds like an interesting use case and a reasonable feature request. As @jdavies-st mentioned, we can likely leverage some existing code, both from ASDF-in-FITS and also from 'exploded' ASDF files, to make this happen.

**Comment by Cadair** [comment]
So I have had a lot of success with doing this, you can see what I have done in this [notebook](https://gist.github.com/Cadair/3252bc47096e44ca5cbf18c80e5e47e7). I would be interested in the next steps with this.

There is a clear seperation point between the section of the code that holds the FITS array reference and the code that then loads that reference. I am very interested in having the loading code be hot-swappable (i.e. not linked to a file) so that I can use fitsio or astropy as I wish, and I think this seperation sits well with @drdavella desire to de-astropy asdf.

Unless there are any major comments on the notebook, I think my next step will be to open a PR for the reference tag and object, and then we can discuss potential ways of storing and opening arrays of references.

**Comment by drdavella** [comment]
@Cadair this looks good to me. I would like to make this as generic as possible so that it could support a wide variety of foreign array references, not just arrays contained in FITS files. Since the loader implementation will be provided by the user anyway, this shouldn't be a problem. We just need to be thoughtful about the kind of metadata that we provide.

**Comment by Cadair** [comment]
I don't know how easy it would be to provide one that wasn't FITS specific given you really need a `hdu_index` for instance. If we wanted to make a generic external reference class where you could define arbitary metadata (maybe by subclassing?) then it could work but you would need a FITS specific one somewhere.

**Comment by drdavella** [comment]
It's possible that we could just provide an `index` field, which in the case of a FITS file would mean an `hdu_index`, but for other file types it could mean something else (or be omitted entirely). We could also add a `filetype` field to indicate which kind of file is being referenced.

**Comment by Cadair** [comment]
Do you have some good examples of other file types that should be supported, so we can test it and make sure it plays well? What about extending it to cover references to other asdf files?

**Comment by drdavella** [comment]
I think the case of referencing external asdf data is interesting, although I wouldn't necessarily want to commit replacing the existing reference infrastructure. The main issue in this case is that finding an array in an external asdf file is not as simple as providing an integer index since it could be anywhere in the tree. However, that might make it more interesting case for testing a generic implementation.

In full disclosure, one of the reasons for wanting to make this non-FITS-specific is that we have already moved the implementation of the FITS tag to Astropy and I have considered moving the corresponding schema to astropy as well. In light of that, I'm not keen on adding new FITS-specific code to ASDF, so if it can be more generic that would be great.

**Comment by Cadair** [comment]
> I'm not keen on adding new FITS-specific code to ASDF

I get this, but it's not tied to any library, just the fact that FITS exits in the world ;)

> I wouldn't necessarily want to commit replacing the existing reference infrastructure

Sure, both could play nice.

> The main issue in this case is that finding an array in an external asdf file is not as simple as providing an integer index since it could be anywhere in the tree.

🤔
