### ISSUE TITLE
JSON references do not handle "file:" scheme

### ISSUE THREAD

**Issue by eschnett** [spacetelescope/asdf#512]
When I prefix the file name in a JSON reference with "file:" to describe the scheme, the Python parser aborts. Since the URI (and thus JSON reference) standard require a scheme to be present, while allowing application-specific abbreviations, the Parser should handle a "file:" prefix.

**Comment by drdavella** [comment]
Hi @eschnett thanks for the feedback! Can you provide an example of your use case?

**Comment by eschnett** [comment]
I have no particular use case. I began experimenting with that feature, and expected that a URL needs to begin with a scheme description such as "file" ("http"). I was hoping that the library could also handle file names directly (it does), but did not expect that it could not handle properly formatted URL. Apart from standards conformance (and documentation?), I don't have a use case.

**Comment by drdavella** [comment]
I added a test for `file:` references in schemas. The code can be found here, and is also included inline below:

https://github.com/drdavella/asdf/blob/57c04faf11cba1723a2f3546ebe76cd5a10f5daf/asdf/tests/test_schema.py#L173-L194

```python
def test_load_schema_with_file_url(tmpdir):
    schema_def = """
%YAML 1.1
%TAG !asdf! tag:stsci.edu:asdf/
---
$schema: "http://stsci.edu/schemas/asdf/asdf-schema-1.0.0"
id: "http://stsci.edu/schemas/asdf/nugatory/nugatory-1.0.0"
tag: "tag:stsci.edu:asdf/nugatory/nugatory-1.0.0"

type: object
properties:
  foobar:
      $ref: "{}"

required: [foobar]
...
    """.format(resolver.default_resolver('tag:stsci.edu:asdf/core/ndarray-1.0.0'))
    schema_path = tmpdir.join('nugatory.yaml')
    schema_path.write(schema_def.encode())


    schema_tree = schema.load_schema(str(schema_path), resolve_references=True)
    schema.check_schema(schema_tree)
```

In order to test using a schema reference that actually maps to a schema file on disk, I used the function `default_resolver` from `asdf.resolver`. This maps a tag reference to a formatted file URL, which should look something like the following:

`file:///path/to/asdf/asdf-standard/schemas/stsci.edu/asdf/core/ndarray-1.0.0.yaml`

You can confirm by calling `default_resolver` in an interactive session, or by putting a print statement in the test and running with `pytest --capture=no`.

The test passes, so as far as I can tell the `file:` schema appears to be perfectly acceptable in JSON references, unless I have misunderstood your use case. As a sanity check, the test will fail if you pass an invalid tag reference as the argument to `default_resolver`.
